<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="User" failures="1" tests="6" name="com.CRM.OrganisationTest.TestScriptForOrganisation" time="151.544" errors="0" timestamp="2024-11-08T12:38:11 IST" skipped="2">
  <testcase classname="com.CRM.OrganisationTest.TestScriptForOrganisation" name="createOrgWithCredentials" time="20.977"/>
  <system-out>
    <![CDATA[I--Test Execution Starts.....
I--Test Execution Success.....]]>
  </system-out>
  <testcase classname="com.CRM.OrganisationTest.TestScriptForOrganisation" name="createOrgWithContact" time="21.569"/>
  <system-out>
    <![CDATA[I--Test Execution Starts.....
I--Test Execution Success.....]]>
  </system-out>
  <testcase classname="com.CRM.OrganisationTest.TestScriptForOrganisation" name="createOrg" time="20.185">
    <skipped/>
  </testcase> <!-- createOrg -->
  <system-out>
    <![CDATA[I--Test Execution Starts.....
I--Test Execution Skipped.....]]>
  </system-out>
  <testcase classname="com.CRM.OrganisationTest.TestScriptForOrganisation" name="createOrg" time="19.976">
    <skipped/>
  </testcase> <!-- createOrg -->
  <system-out>
    <![CDATA[I--Test Execution Starts.....
I--Test Execution Skipped.....]]>
  </system-out>
  <testcase classname="com.CRM.OrganisationTest.TestScriptForOrganisation" name="createOrg" time="20.645">
    <failure message="The following asserts failed:
	Organization is created expected [Facebook_60095] but found [Facebook_6009]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Organization is created expected [Facebook_60095] but found [Facebook_6009]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.CRM.ObjectRepository.OrganisationInfoPage.verifyOrgName(OrganisationInfoPage.java:119)
at com.CRM.OrganisationTest.TestScriptForOrganisation.createOrg(TestScriptForOrganisation.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:155)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:169)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:88)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:137)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
    </failure>
  </testcase> <!-- createOrg -->
  <system-out>
    <![CDATA[I--Test Execution Starts.....
I--Test Execution Fails.....
Screenshot is Taken....]]>
  </system-out>
  <testcase classname="com.CRM.OrganisationTest.TestScriptForOrganisation" name="deleteOrg" time="48.192"/>
  <system-out>
    <![CDATA[I--Test Execution Starts.....
Organisation deleted Successfully.......
I--Test Execution Success.....]]>
  </system-out>
</testsuite> <!-- com.CRM.OrganisationTest.TestScriptForOrganisation -->
